# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clothing_store_development

test:
  <<: *default
  database: clothing_store_test

production:
  <<: *default
  database: clothing_store_production
  username: clothing_store
  password: <%= ENV['CLOTHING_STORE_DATABASE_PASSWORD'] %>
